name: kaelenlegacy
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flame: ^1.11.0 # O la última versión disponible
  cupertino_icons: ^1.0.8
  video_player: ^2.5.1 # O la última versión disponible
  supabase_flutter: ^2.10.3
  flutter_dotenv: ^6.0.0
  flutter_secure_storage: ^9.2.4
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/
    - assets/images/
    - assets/fonts/
    - assets/Nivel1/
  fonts:
    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel/Cinzel-Black.ttf
          weight: 900
        - asset: assets/fonts/Cinzel/Cinzel-Medium.ttf
          weight: 500
    - family: Spectral
      fonts:
        - asset: assets/fonts/spectral/Spectral-Italic.ttf
        - asset: assets/fonts/spectral/Spectral-Light.ttf
          weight: 300